import { Inter } from "next/font/google";
import "./globals.css";
import UseAllContext from "@/context/all-context";
import NextTopLoader from "nextjs-toploader";
import SessionWrapper from "@/components/session-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next-Chat",
    template: "%s | Next - Chat"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <NextTopLoader color="#f0f0f0" height={1} showSpinner={false} />
          <UseAllContext>
            {children}
          </UseAllContext>
          <script src="https://cdn.jsdelivr.net/npm/preline@2.3.0/dist/preline.min.js"></script>
        </body>
      </SessionWrapper>
    </html>
  );
}
